### ISSUE TITLE
✨ Basic Setting for HomePage with Lib

### ISSUE THREAD

**Issue by clyde-yoonjae** [spring-bud/mate-fe#2]
### ✨ 진행할 작업 설명

```markdown
1. ShadCn 셋팅
2. Home에서 사용될 ShadCn 컴포넌트 생성
3. Home에서 사용할 Mock데이터 추가(BannerImg & UserImg)
```

### 🚀 TODO

- [x] ShadCn 설치
- [x] react-icon 설치
- [x] frammer-motion 설치
- [x] Home에서 사용될 ShadCn 컴포넌트 생성
- [x] Home에서 사용할 Mock데이터 추가(BannerImg & UserImg)

### 🐋 연관된 이슈

- closed
- resolved
