### ISSUE TITLE
✨ Product등록 에디터 구현

### ISSUE THREAD

**Issue by clyde-yoonjae** [spring-bud/mate-fe#6]
### ✨ 진행할 작업 설명

에디터 및 프리뷰어 구현

### 🚀 TODO

- [x] 에디터 설정
- [x] 프리뷰 설정
- [x] 이미지 드래그&드롭 구현(마우스 커서위치)
- [x] 첫 번째 사진 배너이미지로 설정
- [x] 에디터 내부 이미지 업로드 로직
- [x] 임시저장

### 🐋 연관된 이슈

- closed
- resolved
